name: "Close stale issues"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open two years with no activity. Remove the stale label or leave a comment to keep it open, or this will be closed in 7 days.'
        days-before-stale: 730
        days-before-close: 7
